# Generated by Django 4.0.3 on 2022-03-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_plan_rename_tasks_task_review_planitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
